
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema
{
	public partial class AdministrarDepartamentos
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtNombreDept;

		private global::Gtk.Entry txtCantEmp;

		private global::Gtk.Entry txtJefeDept;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvListaDepartamentos;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Button btnModificar;

		private global::Gtk.Button btnRegresar;

		private global::Gtk.Label label4;

		private global::Gtk.Entry txtExtDept;

		private global::Gtk.Label label5;

		private global::Gtk.Entry txtEmailDept;

		private global::Gtk.Entry txtIdDepto;

		private global::Gtk.Label label6;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Sistema.AdministrarDepartamentos
			this.Name = "Sistema.AdministrarDepartamentos";
			this.Title = global::Mono.Unix.Catalog.GetString("AdministrarDepartamentos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sistema.AdministrarDepartamentos.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Departamento");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 16;
			w1.Y = 27;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad Empleados");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w2.X = 32;
			w2.Y = 77;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Jefe Depto");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w3.X = 91;
			w3.Y = 124;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtNombreDept = new global::Gtk.Entry();
			this.txtNombreDept.WidthRequest = 277;
			this.txtNombreDept.CanFocus = true;
			this.txtNombreDept.Name = "txtNombreDept";
			this.txtNombreDept.IsEditable = true;
			this.txtNombreDept.InvisibleChar = '•';
			this.fixed1.Add(this.txtNombreDept);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtNombreDept]));
			w4.X = 196;
			w4.Y = 22;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtCantEmp = new global::Gtk.Entry();
			this.txtCantEmp.WidthRequest = 151;
			this.txtCantEmp.CanFocus = true;
			this.txtCantEmp.Name = "txtCantEmp";
			this.txtCantEmp.IsEditable = true;
			this.txtCantEmp.InvisibleChar = '•';
			this.fixed1.Add(this.txtCantEmp);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCantEmp]));
			w5.X = 195;
			w5.Y = 68;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtJefeDept = new global::Gtk.Entry();
			this.txtJefeDept.WidthRequest = 267;
			this.txtJefeDept.CanFocus = true;
			this.txtJefeDept.Name = "txtJefeDept";
			this.txtJefeDept.IsEditable = true;
			this.txtJefeDept.InvisibleChar = '•';
			this.fixed1.Add(this.txtJefeDept);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtJefeDept]));
			w6.X = 194;
			w6.Y = 111;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvListaDepartamentos = new global::Gtk.TreeView();
			this.tvListaDepartamentos.WidthRequest = 451;
			this.tvListaDepartamentos.HeightRequest = 186;
			this.tvListaDepartamentos.CanFocus = true;
			this.tvListaDepartamentos.Name = "tvListaDepartamentos";
			this.GtkScrolledWindow.Add(this.tvListaDepartamentos);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w8.X = 17;
			w8.Y = 287;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btnGuardar);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnGuardar]));
			w9.X = 69;
			w9.Y = 242;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w10.X = 357;
			w10.Y = 245;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnModificar = new global::Gtk.Button();
			this.btnModificar.CanFocus = true;
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.UseUnderline = true;
			this.btnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.btnModificar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnModificar]));
			w11.X = 209;
			w11.Y = 240;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.btnRegresar);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnRegresar]));
			w12.X = 21;
			w12.Y = 502;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Ext");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w13.X = 65;
			w13.Y = 165;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtExtDept = new global::Gtk.Entry();
			this.txtExtDept.CanFocus = true;
			this.txtExtDept.Name = "txtExtDept";
			this.txtExtDept.IsEditable = true;
			this.txtExtDept.InvisibleChar = '•';
			this.fixed1.Add(this.txtExtDept);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtExtDept]));
			w14.X = 98;
			w14.Y = 154;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Email");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w15.X = 295;
			w15.Y = 159;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtEmailDept = new global::Gtk.Entry();
			this.txtEmailDept.CanFocus = true;
			this.txtEmailDept.Name = "txtEmailDept";
			this.txtEmailDept.IsEditable = true;
			this.txtEmailDept.InvisibleChar = '•';
			this.fixed1.Add(this.txtEmailDept);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtEmailDept]));
			w16.X = 345;
			w16.Y = 153;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtIdDepto = new global::Gtk.Entry();
			this.txtIdDepto.Sensitive = false;
			this.txtIdDepto.CanFocus = true;
			this.txtIdDepto.Name = "txtIdDepto";
			this.txtIdDepto.IsEditable = true;
			this.txtIdDepto.InvisibleChar = '•';
			this.fixed1.Add(this.txtIdDepto);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtIdDepto]));
			w17.X = 288;
			w17.Y = 197;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("ID");
			this.fixed1.Add(this.label6);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
			w18.X = 257;
			w18.Y = 204;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 557;
			this.DefaultHeight = 544;
			this.Show();
			this.tvListaDepartamentos.CursorChanged += new global::System.EventHandler(this.OnTvListaDepartamentosCursorChanged);
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.btnModificar.Clicked += new global::System.EventHandler(this.OnBtnModificarClicked);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
		}
	}
}
